---
- name: namespace check
  hosts: localhost
  gather_facts: true
  connection: local

  collections:
    - community.kubernetes
  
  environment:
    -  KUBECONFIG: "{{ config_file_path }}"

  tasks:
    - name: Ensure the myapp Namespace exists.
      k8s:
        api_version: v1
        kind: Namespace
        name: magic
        state: present
